version: "0.2"
words:
  - adksetup
  - autofitter
  - bindkey
  - browserslist
  - Bubuntu
  - clsx
  - dchp
  - dism
  - distro
  - donwloaded
  - easyops
  - esphome
  - fontconfig
  - freetype
  - gdbm
  - geoip
  - geoipupdate
  - geolocation
  - ghostscript
  - giflib
  - graphviz
  - groff
  - hotspot
  - jbigkit
  - libfontenc
  - libgd
  - libmaxminddb
  - libpaper
  - libsodium
  - libzmq
  - localdomain
  - lywsd03mmc
  - macaddress
  - maintainership
  - maxmind
  - maxminddb
  - mkdir
  - mkfontscale
  - msiexec
  - nasip
  - ndpi
  - netpbm
  - ntop
  - ntopng
  - ooobe
  - openpgm
  - pfsense
  - ppem
  - protobuf
  - smartctl
  - smartmontools
  - ssid
  - thermalzone
  - timeseries
  - TOTP
  - truetype
  - tsdb
  - uchardet
  - unattend
  - verdana
  - vnstat
  - webfonts
  - webp
  - wemos
  - wrover
  - xiaomi
  - xorg
  - Zabbix
  - zstd
