version: "0.2"
words:
  - adksetup
  - dism
  - donwloaded
  - fontconfig
  - geoipupdate
  - lywsd03mmc
  - maxmind
  - nasip
  - ndpi
  - ntopng
  - ooobe
  - timeseries
  - unattend
  - vnstat
  - wemos
  - xiaomi
  - esphome
  - wrover
  - ssid
  - localdomain
  - hotspot
  - bindkey
  - freetype
  - gdbm
  - giflib
  - graphviz
  - groff
  - jbigkit
  - libfontenc
  - libgd
  - libmaxminddb
  - libpaper
  - libsodium
  - libzmq
  - mkfontscale
  - openpgm
  - protobuf
  - uchardet
  - webfonts
  - webp
  - zstd
  - freetype
  - truetype
  - autofitter
  - maintainership
  - ghostscript
  - netpbm
  - xorg
  - verdana
  - ppem
  - geolocation
  - geoip
  - maxminddb
  - macaddress
  - dchp
  - ntop
  - pfsense
  - mkdir
  - tsdb
  - msiexec
  - thermalzone
  - easyops
  - clsx
  - browserslist
