version: "0.2"
words:
  - adksetup
  - AUTOCERT
  - autofitter
  - AUTOUPDATE
  - badblocks
  - bindkey
  - browserslist
  - Bubuntu
  - clsx
  - CNAME
  - CONFIGUPDATE
  - dchp
  - dism
  - distro
  - donwloaded
  - easyops
  - esphome
  - fontconfig
  - freetype
  - gdbm
  - GENSUDO
  - geoip
  - geoipupdate
  - geolocation
  - ghostscript
  - giflib
  - graphviz
  - groff
  - hotspot
  - INSTALLDIR
  - jbigkit
  - libfontenc
  - libgd
  - libmaxminddb
  - libpaper
  - libsodium
  - libzmq
  - localdomain
  - LOGPATH
  - lywsd03mmc
  - macaddress
  - maintainership
  - maxmind
  - maxminddb
  - Memstick
  - mkdir
  - mkfontscale
  - msiexec
  - nasip
  - ndpi
  - netpbm
  - ntop
  - ntopng
  - ooobe
  - openpgm
  - pfsense
  - ppem
  - proto
  - protobuf
  - ronivay
  - SELFUPGRADE
  - smartctl
  - smartmontools
  - ssid
  - thermalzone
  - timeseries
  - TOTP
  - traefik
  - truenas
  - truetype
  - tsdb
  - uchardet
  - umounting
  - unattend
  - USESUDO
  - verdana
  - vnstat
  - webfonts
  - webp
  - wemos
  - wrover
  - xiaomi
  - xorg
  - XOUSER
  - yourdomain
  - YOURPASSWORD
  - Zabbix
  - zstd
